apiVersion: v1
kind: Service
metadata:
  name: netflix-svc
  labels:
    app: my-app-np
spec:
  type: LoadBalancer
  ports:
  - port: 4000
    targetPort: 80
    protocol: TCP
  selector:
    app: my-app-np


# apiVersion: v1
# kind: Service
# metadata:
#   name: netflix-svc
#   labels:
#     app: my-app-np
# spec:
#   type: ExternalName
#   externalName: argocd.ashraf.cyou


# apiVersion: v1
# kind: Service
# metadata:
#   name: netflix-svc
#   namespace: netflix-space
# spec:
#   type: ExternalName
#   externalName: netflix.com
